### PR TITLE
Drop php 5 5 support

### LINKED ISSUE #4: Drop Support for PHP 5.5

### PR DESCRIPTION
**Pull request by elstamey**
updated the `composer.json` and `.travis.yml` configuration files

resolves #4

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Could you update this PR so the PHP constraint matches as discussed here? https://github.com/phergie/plugin-http/pull/5#discussion_r74494372

**Comment by elstamey** [comment]
@WyriHaximus I missed this comment, but I'm curious why you merged it the other way in `plugin-http` repo and requested it be fixed here

**Comment by WyriHaximus** [comment]
@elstamey no problem, I like to keep things like this the same across projects, and I prefer it to be `^5.6 || ^7.0` over `>=5.6`.

**Comment by elstamey** [comment]
Based on your comment in the other, I thought you wanted the order switched, as well `^7.0 || ^5.6`

**Comment by WyriHaximus** [comment]
Yeah that would be perfect, but not a reason not to merge it :smile:

**Comment by elstamey** [comment]
I submitted consistent versions to both repos.

**Comment by WyriHaximus** [comment]
Awesome thank you :+1:

**Pull request merged**
