### PR TITLE
update version of phergie-irc-bot-react and phergie-irc-plugin-react-command

### PR DESCRIPTION
**Pull request by svpernova09**
update version of phergie/phergie-irc-bot-react and phergie/phergie-irc-plugin-react-command

### CODE REVIEW

**Comment by svpernova09** [comment]
@WyriHaximus 

Looks like PHP 5.4 is breaking because the rest of the packages are requiring minimum 5.5 Safe to make that change here as well?

**Comment by WyriHaximus** [comment]
If 5.5 is the new minimum can you bump this package to 5.5 in this PR as well? I'll tag a new major release when the tests pass :+1:

**Comment by svpernova09** [comment]
:+1:

**Comment by svpernova09** [comment]
@WyriHaximus Removed those versions, we're good to go here for merge and tag 2.0

**Comment by WyriHaximus** [comment]
Merged and tagged 4.0.0 on this package: https://github.com/phergie/plugin-dns/releases/tag/4.0.0

**Pull request merged**
